### PR TITLE
add open-all link

### PR DESCRIPTION
**Pull request by Gregory-Pereira**
Addresses #246

### CODE REVIEW

**Comment by Gregory-Pereira** [comment]
After testing, I found that a common behaviour for all modern ad-blockers is to disable multiple page opens for the obvious reasons. While I cannot interact with the specific browsers settings directly from the HTML, I can add alert informing the user of this behaviour that is not immediately apparent under the hood. However if you open the console tag and check errors, you should have a quick way to navigate to unblocking the ad-blocker for that subdomain + domain combo, in this case: `https://instruct-lab-bot.s3.us-east-2.amazonaws.com/`

Knowing this, do we still want this feature @jjasghar

**Comment by Gregory-Pereira** [comment]
As outcome of standup, maybe make this more into a single file, but have a bunch of next buttons which would use anchor tags to route to the next entry...

**Comment by vishnoianil** [comment]
@Gregory-Pereira here is the very raw mockup of what i was thinking of:

Screenshot 2024-04-29 at 11 33 20 PM

We can create one html file, and put content from these yaml files as a frame/slide. Reviewer can press the arrow and it can go to the next set of input (context, question) and answer. That way they don't have to jump between the files and can review all the results through single tab. We can make it even bit more smarter, by not putting all the contents in the html itself, but use script to read these files and display them pretty-print. 

Let me know if you have any other suggestion or if you want to take a stab at it, otherwise i can give it a shot.

**Comment by Gregory-Pereira** [comment]
Partially resolved in #340. The rest has been moved to #346.

**Pull request closed without merging**
